# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install sdl2
      - name: install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libsdl2-image-dev libgtk-3-dev libsdl2-ttf-dev

      # Build main.c
      - name: make main.c
        run: |
          make

  # Test job
  test:
      runs-on: ubuntu-latest
      needs: build
      
      steps:
      - uses: actions/checkout@v3

        # Install sdl2
      - name: install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libsdl2-image-dev libgtk-3-dev libsdl2-ttf-dev

      # Build test.c and run it
      - name: Run unit tests
        run: |
          make test
          ./test
          make network
          ./network test src/neuralnetwork/training_set/0-102.png
          
  deploy:
      runs-on: ubuntu-latest
      needs: test
      
      steps:
      - name: Deploy to gitlab
        uses: wei/git-sync@v3
        with:
          source_repo: git@github.com:DaiF1/OCR.git
          source_branch: main
          destination_repo: julie.fiadino@git.cri.epita.fr:p/2026-prs-s3-project/julie.fiadino.git
          destination_branch: master
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          
